### ISSUE TITLE
invalid go version '1.22.0': must match format 1.23

### ISSUE THREAD

**Issue by chaksn** [siderolabs/conform#251]
Issue Summary:
Encountering an error when attempting to install github.com/siderolabs/conform at version v0.1.0-alpha.28, while no such issue exists with version v0.1.0-alpha.27. Using Go version 1.13.

Expected Behavior:
Expecting to successfully install and use version v0.1.0-alpha.28 of github.com/siderolabs/conform.

Actual Behavior:
go install: github.com/siderolabs/conform/cmd/conform@latest (in github.com/siderolabs/conform@v0.1.0-alpha.28): go.mod:3: invalid go version '1.22.0': must match format 1.23

Additional Information:
Go version: 1.13
No such issue encountered with version v0.1.0-alpha.27.

![Screenshot 2024-02-25 at 8 25 07 AM](https://github.com/siderolabs/conform/assets/35711357/ffe591ff-05be-4fe9-b3a8-b1995122e787)

**Comment by frezbo** [comment]
Go 1.13 is too old to support new conform (basically newer go.mod patch version support)

**Comment by heismehrab** [comment]
I have the same error with Golang version 1.22.0 linux/amd64 . Any updates?

**Comment by frezbo** [comment]
> I have the same error with Golang version 1.22.0 linux/amd64 . Any updates?

not sure what's the issue, works for me:

```bash
❯ go install github.com/siderolabs/conform/cmd/conform@latest
go: downloading github.com/siderolabs/conform v0.1.0-alpha.30
~ took 5s119ms 
❯ go version
go version go1.22.0 linux/amd64
~ 
❯ 
~

**Comment by heismehrab** [comment]
It's strange, I cannot figure out the problem. I appreciate it if you share your ideas about it:

```bash
$ sudo go install github.com/siderolabs/conform/cmd/conform@latest

go: github.com/siderolabs/conform/cmd/conform@latest (in github.com/siderolabs/conform@v0.1.0-alpha.30): go.mod:3: invalid go version '1.22.0': must match format 1.23
```


in go.mod i set version 1.22 

```golang
module bluh

go 1.22
```

**Comment by Dileesha-abilash** [comment]
just changing the version in file works 1.xx.x to 1.xx

**Comment by stephenwhy** [comment]
> just changing the version in go.mod file works 1.xx.x to 1.xx

Oh, my God, it works, but I don't see why it should work

**Comment by njupt99lee** [comment]
> just changing the version in go.mod file works 1.xx.x to 1.xx

it works but why？

**Comment by mj3c** [comment]
First, check the Go version you have installed with `go version`.

If you are using Go 1.20 or older, your project's `go.mod` has to specify the version _without_ the patch number, so for example `go 1.19`.

If you are using Go 1.21 or newer, your project's `go.mod` can specify the version with or without the patch number, both seem to work.

Hope this helps.

**Comment by Stamp9** [comment]
go run cmd/main.go
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> txpool-viz/internal/controller/routes.RegisterRoutes.func1 (4 handlers)
[GIN-debug] GET    /transactions             --> txpool-viz/internal/controller/handler.(*Handler).GetLatestTransactions-fm (4 handlers)
[GIN-debug] GET    /transaction/:txHash      --> txpool-viz/internal/controller/handler.(*Handler).GetTransactionDetails-fm (4 handlers)
2025-05-15T09:41:21Z INF internal/controller/controller.go:95 > Serving frontend at http://localhost:8080
2025-05-15T09:41:21Z ERR internal/controller/controller.go:67 > API server failed FIELDS=[{"error":"listen tcp :42069: bind: address already in use"}]
2025-05-15T09:41:21Z ERR internal/transactions/stream.go:39 > error connecting to websocket: failed to WebSocket dial: unexpected url scheme: "" FIELDS=[{"endpoint":"erigon","url":""}]
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x870b90]

goroutine 73 [running]:
github.com/coder/websocket.(*Conn).casClosing(...)
        /home/raphina/go/pkg/mod/github.com/coder/websocket@v1.8.13/close.go:332
github.com/coder/websocket.(*Conn).Close(0xc0004b3b48?, 0x43e765?, {0xa3f116?, 0xc000480fc0?})
        /home/raphina/go/pkg/mod/github.com/coder/websocket@v1.8.13/close.go:103 +0x50
panic({0x96bb00?, 0xe71f90?})
        /snap/go/10888/src/runtime/panic.go:792 +0x132
github.com/coder/websocket.(*Conn).reader(0x0, {0xb2a8b0, 0xc0001a4c80})
        /home/raphina/go/pkg/mod/github.com/coder/websocket@v1.8.13/read.go:369 +0x8f
github.com/coder/websocket.(*Conn).Reader(...)
        /home/raphina/go/pkg/mod/github.com/coder/websocket@v1.8.13/read.go:37
github.com/coder/websocket.(*Conn).Read(0xc000276320?, {0xb2a8b0?, 0xc0001a4c80?})
        /home/raphina/go/pkg/mod/github.com/coder/websocket@v1.8.13/read.go:43 +0x1e
txpool-viz/internal/transactions.streamEndpoint({0xb2a8b0, 0xc0001a4c80}, {{0xc000276320, 0x6}, {0xc000026918, 0x15}, {0x0, 0x0}, 0x0, 0xc0000a2698}, ...)
        /home/raphina/cloned/txpool-viz/internal/transactions/stream.go:61 +0x2d5
txpool-viz/internal/transactions.Stream.func1({{0xc000276320, 0x6}, {0xc000026918, 0x15}, {0x0, 0x0}, 0x0, 0xc0000a2698})
        /home/raphina/cloned/txpool-viz/internal/transactions/stream.go:29 +0xdf
created by txpool-viz/internal/transactions.Stream in goroutine 16
        /home/raphina/cloned/txpool-viz/internal/transactions/stream.go:27 +0x93
exit status 2
make: *** [Makefile:14: run-app] Error 1
